import Papa from 'papaparse';
import { prisma } from '@/db/prisma';
import { writePdf, header, tableRow } from '@/modules/dispatch/pdf/_pdfBase';
import { buildOverview, buildPnlSummary, DateRange } from './reports.service';

/** PDF export of the Overview + P&L for a date range. */
export async function exportOverviewPdf(opts: { tenantId: string; range: DateRange }): Promise<{ pdfUrl: string }> {
  const tenant = await prisma.tenant.findUnique({ where: { id: opts.tenantId } });
  if (!tenant) throw new Error('Tenant not found');

  const overview = await buildOverview(opts.tenantId, opts.range);
  const pnl = await buildPnlSummary(opts.tenantId, opts.range);

  const fileName = `report-overview-${tenant.prefix}-${opts.range.endDate.toISOString().slice(0, 10)}-${Date.now()}.pdf`;
  const written = await writePdf(fileName, (doc) => {
    doc.addPage({ size: 'A4', margin: 36 });
    header(doc, `${tenant.name} — Performance Report`,
      `${opts.range.startDate.toISOString().slice(0, 10)} → ${opts.range.endDate.toISOString().slice(0, 10)}`);

    doc.font('Helvetica-Bold').fontSize(12).text('Key metrics');
    doc.font('Helvetica').fontSize(10).moveDown(0.3);
    const k = overview.kpi;
    [
      ['Total orders', k.totalOrders],
      ['Confirmation rate', `${k.confirmationRatePct}%`],
      ['Delivery rate', `${k.deliveryRatePct}%`],
      ['RTO rate', `${k.rtoRatePct}%`],
      ['Avg order value', `Rs ${k.avgOrderValuePkr}`],
      ['Gross revenue (delivered)', `Rs ${k.grossRevenuePkr.toLocaleString()}`],
      ['Recognized revenue', `Rs ${pnl.recognizedRevenue.toLocaleString()}`],
      ['Net profit', `Rs ${pnl.netProfit.toLocaleString()}`],
      ['Margin', `${pnl.marginPct}%`],
    ].forEach(([k1, v]) => {
      doc.text(`${k1}:`, { continued: true }).text(`  ${v}`, { align: 'right' });
    });

    doc.moveDown();
    doc.font('Helvetica-Bold').fontSize(12).text('Daily breakdown (last 7 days)');
    doc.moveDown(0.3);
    tableRow(doc, [
      { text: 'Date',      width: 100 },
      { text: 'Orders',    width: 70, align: 'right' },
      { text: 'Delivered', width: 70, align: 'right' },
      { text: 'RTO',       width: 60, align: 'right' },
      { text: 'Revenue',   width: 100, align: 'right' },
    ], { bold: true });
    overview.daily.forEach((d) => {
      tableRow(doc, [
        { text: d.date, width: 100 },
        { text: String(d.orders), width: 70, align: 'right' },
        { text: String(d.delivered), width: 70, align: 'right' },
        { text: String(d.rto), width: 60, align: 'right' },
        { text: `Rs ${d.revenue.toFixed(0)}`, width: 100, align: 'right' },
      ]);
    });

    doc.moveDown();
    doc.font('Helvetica-Bold').fontSize(12).text('Auto-insights');
    doc.font('Helvetica').fontSize(10).moveDown(0.3);
    if (overview.insights.length === 0) doc.text('No insights flagged for this period.');
    overview.insights.forEach((i) => doc.text(`• ${i}`));

    doc.moveDown();
    doc.font('Helvetica').fontSize(8).fillColor('#999');
    doc.text(`Generated by ${tenant.name} on ${new Date().toISOString()}`, { align: 'center' });
  });

  return { pdfUrl: written.publicUrl };
}

/** CSV export of all orders in a range. */
export async function exportOrdersCsv(opts: { tenantId: string; range: DateRange }): Promise<{ csv: string; rowCount: number }> {
  const orders = await prisma.order.findMany({
    where: { tenantId: opts.tenantId, createdAt: { gte: opts.range.startDate, lte: opts.range.endDate } },
    take: 50_000,
    orderBy: { createdAt: 'desc' },
  });

  const rows = orders.map((o) => ({
    order_id: o.id,
    shopify_order_number: o.shopifyOrderNumber ?? '',
    created_at: o.createdAt.toISOString(),
    status: o.status,
    customer: o.customerName,
    phone: o.phone,
    city: o.city,
    amount_pkr: Number(o.amount).toFixed(2),
    payment: o.paymentStatus,
    courier: o.courierType ?? '',
    tracking: o.trackingNumber ?? '',
    cod_status: o.codRemittanceStatus,
    delivered_at: o.deliveredAt?.toISOString() ?? '',
    rto_at: o.rtoAt?.toISOString() ?? '',
    rto_reason: o.rtoReasonCategory ?? '',
  }));

  const csv = Papa.unparse(rows);
  return { csv, rowCount: rows.length };
}
